export const gender = ["Male", "Female"];

export const MaritalStatus = [
  "NEVER_MARRIED",
  "DIVORCED",
  "WIDOWED",
  // "ANULLED",
  "AWAITING_DIVORCE",
];

export const MotherTongue = [
  "ASSAMESE",
  "AWADHI",
  "BENGALI",
  "BHOJPURI",
  "BODO",
  "DOGRI",
  "ENGLISH",
  "GARHWALI",
  "GUJARATI",
  "HARYANAVI",
  "HIMACHALI",
  "HINDI",
  "KANNADA",
  "KASHMIRI",
  "KONKANI",
  "MAITHILI",
  "MALAYALAM",
  "MARATHI",
  "MARWARI",
  "MEITEI",
  "NEPALI",
  "ODIA",
  "PUNJABI",
  "RAJASTHANI",
  "SANSKRIT",
  "SANTALI",
  "SIKKIMESE",
  "SINDHI",
  "TAMIL",
  "TELUGU",
  "URDU",
  "GERMAN",
  "SPANISH",
  "FRENCH",
  "MANDARIN",
  "RUSSIAN",
  "JAPANESE",
  "PORTUGUESE",
  "OTHER",
];

export const Religion = [
  "HINDU",
  "JAIN_DASH_DIGAMBER",
  "JAIN_DASH_SHWETAMBER",
  "MUSLIM_DASH_SHIA",
  "MUSLIM_DASH_SUNNI",
  "CHRISTIAN",
  "SIKH",
];

export const Height = [
  "48",
  "49",
  "50",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "60",
  "61",
  "62",
  "63",
  "64",
  "65",
  "66",
  "67",
  "68",
  "69",
  "70",
  "71",
  "72",
  "73",
  "74",
  "75",
  "76",
  "77",
  "78",
  "79",
  "80",
  "81",
  "82",
  "83",
  "84",
];

export const Disability = [
  "NONE",
  "MENTALLY_CHALLENGED",
  "PHYSICALLY_CHALLENGED",
];

export const MajorDisease = [
  "NONE",
  "CANCER",
  "HIV_POSITIVE",
  "THALASSEMIA",
  "OTHER",
];

export const DietaryChoice = [
  "VEGAN",
  "JAIN",
  "VEGETARIAN",
  "EGGETARIAN",
  "NON_VEGETARIAN",
];

// export const City =[]

// export const Drink AND Smoke = Boolean

export const Degrees = [
  // Engineering/Design
  "B_dot_Arch",
  "B_dot_Des",
  "B_dot_E_slash_B_dot_Tech",
  "B_dot_Pharma",
  "M_dot_Arch",
  "M_dot_Des",
  "M_dot_E_slash_M_dot_Tech",
  "M_dot_Pharma",
  "MS_openbr_Engineering_closebr",
  //Computers
  "B_dot_IT",
  "BCA",
  "MCA_slash_PGDCA",
  // Finance/Commerce
  "B_dot_Com",
  "CA",
  "CFA",
  "CS",
  "ICWA",
  "M_dot_Com",
  //Management
  "BBA",
  "BHM",
  "MBA_slash_PGDM",
  // Medicine
  "BAMS",
  "BDS",
  "BHMS",
  "BPT",
  "BVSc",
  "DM",
  "MBBS",
  "MCh",
  "MD",
  "MDS",
  "MPT",
  "MS_openbr_Medicine_closebr",
  //Law
  "BL_slash_LLB",
  "ML_slash_LLM",
  //Arts/Science
  "B_dot_A",
  "B_dot_Ed",
  "B_dot_Sc",
  "BFA",
  "BJMC",
  "M_dot_A",
  "M_dot_Ed",
  "M_dot_Sc",
  "MFA",
  "MJMC",
  "MSW",
  // Doctorate
  "M_dot_Phil",
  "Ph_dot_D",
  // Non Graduate
  "High_School",
  "Trade_School",
  "Diploma",
  //Others
  "Other",
];

export const TypeOfIdProof = [
  "AADHAR",
  "Driving_License",
  "PAN",
  "Passport",
  // Voter_ID,
];

export const EmployedIn = [
  "PRIVATE_SECTOR",
  "PUBLIC_SECTOR",
  "CIVIL_SERVICES",
  "DEFENCE",
  "BUSINESS_OR_SELF_EMPLOYED",
  "NOT_WORKING",
];

export const Occupation = [
  "Admin_Professional",
  "Clerk",
  "Operator_or_Technician",
  "Secretary_or_Front_Office",
  "Actor_or_Model",
  "Advertising_Professional",
  "Film_or_Entertainment_Professional",
  "Journalist",
  "Media_Professional",
  "PR_Professional",
  "Agriculture_Professional",
  "Farming",
  "Airline_Professional",
  "Flight_Attendant",
  "Pilot",
  "Architect",
  "Air_Force",
  "Army",
  "Other_Defence_Services",
  "Navy",
  "BPO_or_ITeS_Professional",
  "Customer_Service",
  "Accounting_Professional",
  "Auditor",
  "Banking_Professional",
  "Chartered_Accountant",
  "Finance_Professional",
  "Civil_Services",
  "Analyst",
  "Consultant",
  "Corporate_Communication",
  "Corporate_Planning",
  "HR_Professional",
  "Marketing_Professional",
  "Operations_Management",
  "Product_Manager",
  "Program_Manager",
  "Project_Manager_dash_IT",
  "Project_Manager_dash_Non_IT",
  "Sales_Professional",
  "Sr_Manager_or_Manager",
  "Subject_Matter_Expert",
  "Education_Professional",
  "Educational_Institution_Owner",
  "Librarian",
  "Professor_or_Lecturer",
  "Research_Professional",
  "Research_Assistant",
  "PhD_Student_On_Stipend",
  "Scientist",
  "Teacher",
  "Electronics_Engineer",
  "Hardware_or_Telecom_Engineer",
  "Non_dash_IT_Engineer",
  "Quality_Assurance_Engineer",
  "Hotels_or_Hospitality_Professional",
  "Law_Enforcement_Officer",
  "Police",
  "Lawyer_And_Legal_Professional",
  "Mariner",
  "Merchant_Naval_Officer",
  "Dentist",
  "Doctor",
  "Surgeon",
  "Medical_or_Healthcare_Professional",
  "Nurse",
  "Paramedic",
  "Pharmacist",
  "Physiotherapist",
  "Psychologist",
  "Veterinary_Doctor",
  "Animator",
  "Cyber_or_Network_Security",
  "Project_Lead_dash_IT",
  "Quality_Assurance_Engineer_dash_IT",
  "Software_Professional",
  "UI_or_UX_Designer",
  "Web_or_Graphic_Designer",
  "CXO_or_Chairman_or_President_or_Director",
  "VP_or_AVP_or_GM_or_DGM",
  "Agent",
  "Artist",
  "Beautician",
  "Broker",
  "Business_Owner_or_Entrepreneur",
  "Fashion_Designer",
  "Fitness_Professional",
  "Interior_Designer",
  "Politician",
  "Security_Professional",
  "Singer",
  "Social_Services_or_NGO_or_Volunteer",
  "Sportsperson",
  "Travel_Professional",
  "Writer",
  "Looking_For_Job",
  "Not_Working",
  "Retired",
  "Student",
  "Others",
];

export const NotWorkingOccuptation = [
  "Looking_For_Job",
  "Not_Working",
  "Retired",
  "Student",
];

export const AnnualIncome = [
  "NO_INCOME",
  "UPTO_FIFTY_THOUSAND",
  "FIFTY_THOUSAND_TO_ONE_LAKH",
  "ONE_LAKH_TO_TWO_LAKH",
  "TWO_LAKH_TO_FIVE_LAKH",
  "FIVE_LAKH_TO_TEN_LAKH",
  "TEN_LAKH_TO_TWENTY_LAKH",
  "TWENTY_LAKH_TO_THIRTY_FIVE_LAKH",
  "THIRTY_FIVE_LAKH_TO_FIFTY_LAKH",
  "FIFTY_LAKH_TO_SEVENTY_FIVE_LAKH",
  "SEVENTY_FIVE_LAKH_TO_ONE_CRORE",
  "ONE_CRORE_TO_FIVE_CRORE",
  "FIVE_CRORE_TO_TEN_CRORE",
  "MORE_THAN_TEN_CRORE",
];

export const UserSource = [
  "Google",
  "YouTube",
  "Facebook",
  "Instagram",
  "Twitter",
  "LinkedIn",
  "Friend_slash_Relative",
  "Other",
];

export const ProfileManagedBy = [
  "SELF",
  "PARENT",
  "SIBLING",
  "FRIEND",
  "RELATIVE",
];
